### ISSUE TITLE
startWebSpeech is not a function

### ISSUE THREAD

**Issue by Polariis-ai** [OvidijusParsiunas/speech-to-element#2]
Hi there

I installed and imported speech-to-element in my project but face some issue:

```typescript
import SpeechToElement from 'speech-to-element'

export class STTManager {
  constructor() {
    const userLanguage = 'fr-FR'
    SpeechToElement.startWebSpeech({
      language: userLanguage,
    })
  }
}
```

I get this error on the console:
```
Uncaught TypeError: speech_to_element__WEBPACK_IMPORTED_MODULE_1__.startWebSpeech is not a function
```

I tried using `toggle` but same result.

**Comment by OvidijusParsiunas** [comment]
Hi @hermesguideme.

Is this console error displayed when you try to build your project, or is it displayed on the browser?
Also, can you tell me more about what frameworks/bundlers your project is using?

Thankyou!

**Comment by Polariis-ai** [comment]
Hi @OvidijusParsiunas, thanks a lot for the feedback :)

It's displayed on the browser. The idea is to trigger `startWebSpeech` or `toggle` when clicking on a button. On click, the error displays in chrome's developer console.
I'm using `speech_to_element` in a custom npm package development. I'm using `tsup`. For information, [here](https://www.youtube.com/watch?v=xnfdm-s8adI) is the method I used to set my project.

**Comment by OvidijusParsiunas** [comment]
Thankyou for sharing your build info.

I am unfortunately not very familiar on how `tsup` works, hence I am not sure what needs to be changed in this library to make your build work. It may very well be something in the `tsup` configuration itself.
You can also try to fork/clone this repository and following the simple [local setup](https://github.com/OvidijusParsiunas/speech-to-element/tree/main/component#construction_worker-local-setup) instructions to build the project yourself and see if you can identify the issue.

Due to so many unknowns and the limitation of my time I am unfortunately unable to explore this issue any further. However, if you'll find out what the problem is please add a comment in this issue.

Thankyou!
